# Generated by Django 5.1.7 on 2025-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kiné à Domicile', max_length=100)),
                ('contact_email', models.EmailField(default='contact@kineadomicile.fr', max_length=254)),
                ('phone_number', models.CharField(default='+33 1 23 45 67 89', max_length=20)),
                ('address', models.TextField(default='123 Rue de la Kinésithérapie, 75000 Paris')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=30)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('password_policy', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
