# Generated by Django 5.1.7 on 2025-04-21 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_kine_alter_appointment_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_contenu', models.CharField(choices=[('CONSEIL', 'Conseil'), ('VIDEO', 'Vidéo'), ('IMAGE', 'Image')], max_length=10)),
                ('contenu', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='conseils/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_public', models.BooleanField(default=False)),
                ('kine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ManyToManyField(blank=True, related_name='conseils_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conseil',
                'verbose_name_plural': 'Conseils',
                'ordering': ['-date_creation'],
            },
        ),
    ]
