# Generated by Django 5.1.7 on 2025-04-21 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_conseil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement_souhaite', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('reponse', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('kine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de traitement',
                'verbose_name_plural': 'Demandes de traitement',
                'ordering': ['-date_demande'],
            },
        ),
    ]
